### ISSUE TITLE
websocket isnt working 

### ISSUE THREAD

**Issue by scrimscourge** [Shoonya-Dev/ShoonyaApi-py#120]
Traceback (most recent call last):
  File "C:\Users\algotrader\algotrade.py", line 29, in <module>
    api.start_websocket( order_update_callback=event_handler_feed_update,
  File "C:\Users\code\algotrader\Lib\site-packages\NorenRestApiPy\NorenApi.py", line 211, in start_websocket
    self.__websocket = websocket.WebSocketApp(url,
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

**Comment by Shoonya-Dev** [comment]
@scrimscourge 

Greetings from Shoonya!

Thanks for your mail.

Solution:-  pip install websocket_client

Team Shoonya
