### ISSUE TITLE
Getting Invalid Syntax whilte running test_api.py

### ISSUE THREAD

**Issue by ENGINEERDK** [Shoonya-Dev/ShoonyaApi-py#14]
**Hello Guys,
I ran below command to get started, Please help me debugging whats not setup correct.**

deepak@deepak-Lenovo-G50-80:~/Documents/mylocal/ShoonyaApi-py$ python test_api.py 
Traceback (most recent call last):
  File "test_api.py", line 1, in <module>
    from api_helper import ShoonyaApiPy
  File "/home/deepak/Documents/mylocal/ShoonyaApi-py/api_helper.py", line 1, in <module>
    from NorenRestApiPy.NorenApi import  NorenApi
  File "/home/deepak/.local/lib/python2.7/site-packages/NorenRestApiPy/NorenApi.py", line 102
    **logger.warning(f"websocket run forever ended in exception, {e}")
                                                                  ^**
SyntaxError: invalid syntax

I installed requirements.txt already.

Thanks

**Comment by ENGINEERDK** [comment]
I got it working with Python3.
