### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by kingsrook14** [Shoonya-Dev/ShoonyaApi-py#162]
I am getting error when installing dependencies. 

+++
PS E:\Portable\ShoonyaApi-py> pip install -r requirements.txt
Processing e:\portable\shoonyaapi-py\dist\norenrestapi-0.0.28-py2.py3-none-any.whl (from -r requirements.txt (line 1))
Collecting PyYAML==6.0 (from NorenRestApi==0.0.28->-r requirements.txt (line 1))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "E:\Portable\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\Portable\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Portable\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel  
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults    
          self._add_defaults_ext()
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\kingsrook14\AppData\Local\Temp\pip-build-env-n0v_r70y\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
+++

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please clone our GitHub documentation and try again; its working fine.

**Comment by Spongy01** [comment]
No, Even I tried, the latest version (0.0.28) its not working. Then I downloaded the previous version (0.0.22) and it build just fine.

**Comment by Spongy01** [comment]
![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/78701247/10ca1fc8-9aef-4ed2-ae84-526880a6ad33)
This above is when I try to install 0.0.28.

Afterwards I tried installing 0.0.22 and it did just fine.
![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/78701247/33b00e5e-f5b7-4b96-a22c-482bd1e81f1b)

**Comment by arijitn1** [comment]
@Shoonya-Dev @kambalatech @Nikhesh @kingsrook14 @Spongy01 , am I facing the same error, so how to fix this. please help.

**Comment by arijitn1** [comment]
@Spongy01 could you please share link of the version 22, thanks,

**Comment by Spongy01** [comment]
Yes @arijitn1 , It is simple, go to the `/dist ` folder 
![image](https://github.com/user-attachments/assets/d3d4f586-518b-4b3c-8dcc-672251b42080)

Click on the history tab on the top right side to get the commit history.
![image](https://github.com/user-attachments/assets/cf4e2078-a372-4a98-b36e-f2a9b79a9df5)

There you can go to any previous commit which has Ver. 22 by clicking browse repo at this point
![image](https://github.com/user-attachments/assets/2e3528dc-ce44-40b8-a0bf-62c5210f4e56)

Then you can see the ver. 22 and can download from there:
![image](https://github.com/user-attachments/assets/720d5f30-9a03-4b64-9103-a5450e61a172)

I hope this helps!

**Comment by ghost** [comment]
thanks @Spongy01
