### ISSUE TITLE
shonya login failed

### ISSUE THREAD

**Issue by 1223Rinkuraj** [Shoonya-Dev/ShoonyaApi-py#165]
api.start_websocket(
        order_update_callback=event_handler_order_update,
        subscribe_callback=event_handler_quote_update,
        socket_open_callback=open_callback,
        socket_close_callback=event_handler_socket_closed,

**Comment by 1223Rinkuraj** [comment]
[](
[New Text Document.txt](https://github.com/user-attachments/files/15654026/New.Text.Document.txt)

**Comment by 1223Rinkuraj** [comment]
D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>python Self_Trader.py
HI welcome
['आपका स्वागत है, आपका EXCEL SHEET आधारित ALGO TRADING TERMINAL अब तैयार है, शुभकामनाएँ', 'आपका दिन शुभ हो']
Python Trader Excel Based Terminal program initialised
TelegramBotCredential= (6834490857:AAG2W2xtB5_tf5n08LokQ435GT6g8wWbCI8), ReceiverTelegramID=(5584064334)
userid=FA258883,password=Bb12345@,twoFA=067137,vendor_code=FA258883_U,api_secret=2f9edade23eb75e985aec9afa49a8901, imei=abcd1234
{'request_time': '21:47:35 06-06-2024', 'actid': 'FA258883', 'access_type': ['WEB', 'TT', 'MOB', 'API'], 'uname': 'PRANAY KUMAR SARKAR', 'prarr': [{'prd': 'C', 's_prdt_ali': 'CNC', 'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR']}, {'prd': 'M', 's_prdt_ali': 'NRML', 'exch': ['NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'I', 's_prdt_ali': 'MIS', 'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'H', 's_prdt_ali': 'CO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}, {'prd': 'B', 's_prdt_ali': 'BO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}], 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'NIPO', 'prds': ['C']}, {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'BCD', 'prds': ['M', 'I']}, {'exch': 'MCX', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'NCX', 'prds': ['M', 'I']}, {'exch': 'BSTAR', 'prds': ['C']}, {'exch': 'BFO', 'prds': ['M', 'I']}], 'stat': 'Ok', 'susertoken': '866525ef6fb674674f2fccb5b18dd9e314d2d40643c34b182519d260f614686f', 'email': 'omsaiinfotech.siliguri@gmail.com', 'uid': 'FA258883', 'brnchid': 'HO', 'totp_set': '1', 'm_num': '7699993612', 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'], 'exarr': ['NSE', 'NIPO', 'NFO', 'CDS', 'BSE', 'BCD', 'MCX', 'NCX', 'BSTAR', 'BFO'], 'values': ['3', '2', '1'], 'mws': {'3': [], '2': [], '1': [{'exch': 'NSE', 'token': '26017', 'tsym': 'INDIAVIX', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 'ti': '0.05', 'nontrd': '1'}]}, 'brkname': 'FINV', 'dmsg': '', 'lastaccesstime': '1717690655'}
Finvasia intrument token download started, may take upto 2-3 minutes ..
Finvasia intrument token download completed
Traceback (most recent call last):
  File "D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code\Self_Trader.py", line 3073, in <module>
    api.start_websocket(
  File "C:\Users\Sinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\NorenRestApiPy\NorenApi.py", line 211, in start_websocket
    self.__websocket = websocket.WebSocketApp(url,
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>timeout 20

Waiting for 13 seconds, press a key to continue ...

**Comment by 1223Rinkuraj** [comment]
this error show my pc

**Comment by 1223Rinkuraj** [comment]
D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>python Self_Trader.py
HI welcome
['आपका स्वागत है, आपका EXCEL SHEET आधारित ALGO TRADING TERMINAL अब तैयार है, शुभकामनाएँ', 'आपका दिन शुभ हो']
Python Trader Excel Based Terminal program initialised
TelegramBotCredential= (6834490857:AAG2W2xtB5_tf5n08LokQ435GT6g8wWbCI8), ReceiverTelegramID=(xxxxxxxxxxxx)
userid=xxxxxxx,password=xxx2345@,twoFA=067137,vendor_code=Fxxxx3_U,api_secret=2f9edade23eb75e985aec9afa49a8901, imei=abcd1234
{'request_time': '21:47:35 06-06-2024', 'actid': 'FA258883', 'access_type': ['WEB', 'TT', 'MOB', 'API'], 'uname': 'PRANAY KUMAR SARKAR', 'prarr': [{'prd': 'C', 's_prdt_ali': 'CNC', 'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR']}, {'prd': 'M', 's_prdt_ali': 'NRML', 'exch': ['NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'I', 's_prdt_ali': 'MIS', 'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'H', 's_prdt_ali': 'CO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}, {'prd': 'B', 's_prdt_ali': 'BO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}], 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'NIPO', 'prds': ['C']}, {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'BCD', 'prds': ['M', 'I']}, {'exch': 'MCX', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'NCX', 'prds': ['M', 'I']}, {'exch': 'BSTAR', 'prds': ['C']}, {'exch': 'BFO', 'prds': ['M', 'I']}], 'stat': 'Ok', 'susertoken': '866525ef6fb674674f2fccb5b18dd9e314d2d40643c34b182519d260f614686f', 'email': 'omsaiinfotech.siliguri@gmail.com', 'uid': 'FA258883', 'brnchid': 'HO', 'totp_set': '1', 'm_num': '7699993612', 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'], 'exarr': ['NSE', 'NIPO', 'NFO', 'CDS', 'BSE', 'BCD', 'MCX', 'NCX', 'BSTAR', 'BFO'], 'values': ['3', '2', '1'], 'mws': {'3': [], '2': [], '1': [{'exch': 'NSE', 'token': '26017', 'tsym': 'INDIAVIX', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 'ti': '0.05', 'nontrd': '1'}]}, 'brkname': 'FINV', 'dmsg': '', 'lastaccesstime': '1717690655'}
Finvasia intrument token download started, may take upto 2-3 minutes ..
Finvasia intrument token download completed
Traceback (most recent call last):
  File "D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code\Self_Trader.py", line 3073, in <module>
    api.start_websocket(
  File "C:\Users\Sinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\NorenRestApiPy\NorenApi.py", line 211, in start_websocket
    self.__websocket = websocket.WebSocketApp(url,
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>timeout 20

Waiting for 13 seconds, press a key to continue ...

**Comment by SHIVANIUM-GIT** [comment]
> D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>python Self_Trader.py HI welcome ['आपका स्वागत है, आपका EXCEL SHEET आधारित ALGO TRADING TERMINAL अब तैयार है, शुभकामनाएँ', 'आपका दिन शुभ हो'] Python Trader Excel Based Terminal program initialised TelegramBotCredential= (6834490857:AAG2W2xtB5_tf5n08LokQ435GT6g8wWbCI8), ReceiverTelegramID=(xxxxxxxxxxxx) userid=xxxxxxx,password=xxx2345@,twoFA=067137,vendor_code=Fxxxx3_U,api_secret=2f9edade23eb75e985aec9afa49a8901, imei=abcd1234 {'request_time': '21:47:35 06-06-2024', 'actid': 'FA258883', 'access_type': ['WEB', 'TT', 'MOB', 'API'], 'uname': 'PRANAY KUMAR SARKAR', 'prarr': [{'prd': 'C', 's_prdt_ali': 'CNC', 'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR']}, {'prd': 'M', 's_prdt_ali': 'NRML', 'exch': ['NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'I', 's_prdt_ali': 'MIS', 'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']}, {'prd': 'H', 's_prdt_ali': 'CO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}, {'prd': 'B', 's_prdt_ali': 'BO', 'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}], 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'NIPO', 'prds': ['C']}, {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']}, {'exch': 'BCD', 'prds': ['M', 'I']}, {'exch': 'MCX', 'prds': ['M', 'I', 'H', 'B']}, {'exch': 'NCX', 'prds': ['M', 'I']}, {'exch': 'BSTAR', 'prds': ['C']}, {'exch': 'BFO', 'prds': ['M', 'I']}], 'stat': 'Ok', 'susertoken': '866525ef6fb674674f2fccb5b18dd9e314d2d40643c34b182519d260f614686f', 'email': '[omsaiinfotech.siliguri@gmail.com](mailto:omsaiinfotech.siliguri@gmail.com)', 'uid': 'FA258883', 'brnchid': 'HO', 'totp_set': '1', 'm_num': '7699993612', 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'], 'exarr': ['NSE', 'NIPO', 'NFO', 'CDS', 'BSE', 'BCD', 'MCX', 'NCX', 'BSTAR', 'BFO'], 'values': ['3', '2', '1'], 'mws': {'3': [], '2': [], '1': [{'exch': 'NSE', 'token': '26017', 'tsym': 'INDIAVIX', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 'ti': '0.05', 'nontrd': '1'}]}, 'brkname': 'FINV', 'dmsg': '', 'lastaccesstime': '1717690655'} Finvasia intrument token download started, may take upto 2-3 minutes .. Finvasia intrument token download completed Traceback (most recent call last): File "D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code\Self_Trader.py", line 3073, in api.start_websocket( File "C:\Users\Sinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\NorenRestApiPy\NorenApi.py", line 211, in start_websocket self.__websocket = websocket.WebSocketApp(url, ^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?
> 
> D:\finvesiya\Version_v3 with python source code_100%complete work_03062024_1447hrs.,\Version_v3 with python source code>timeout 20
> 
> Waiting for 13 seconds, press a key to continue ...

can we talk?
