### ISSUE TITLE
No response from api

### ISSUE THREAD

**Issue by manishbadhe** [Shoonya-Dev/ShoonyaApi-py#188]
Last value in 'pe_final_values' column: False
Maximum High Value: BANKNIFTY09OCT24P52000 637.5
place market for buy pe above 637.5 with ltp value 640.2
Traceback (most recent call last):
  File "c:\supertrendstrategy-feature-first_cut\main.py", line 187, in <module>
    main(api=api)
  File "c:\supertrendstrategy-feature-first_cut\main.py", line 86, in main
    place_order(api,live_trade=LIVE_TRADE,symbol=pesymbol_name, main_symbol="BANKNIFTY_PE", qty=QTY, optt="PE", token=PETOKEN)
  File "c:\supertrendstrategy-feature-first_cut\paper_trade.py", line 354, in place_order
    raise ValueError("Error: No response received from the API AND ALSO EXIT ORDER IS NOT PLACED THIS ERROR IS RAISE BY DEVLOPER ")
ValueError: Error: No response received from the API AND ALSO EXIT ORDER IS NOT PLACED THIS ERROR IS RAISE BY DEVLOPER

**Comment by inderweb** [comment]
I am trying with simple test order:-

` response = self.api.get_security_info(exchange = "NFO", token = 52519);
`
or even
`
                responses = self.api.place_order(buy_or_sell='B', product_type='C',
                exchange='NFO', tradingsymbol='NIFTY02JAN2025C23600',
                quantity=1, discloseqty=0,price_type='MKT', price=0, trigger_price=None,
                retention='DAY', remarks='my_order_001')
`

Getting None response from API. no error no message even i follow same example as per Python API. Getting none while getting positions as well.
I am able to get:-
- Login
- Balance info
- searchscript
