### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by chandre-gowda** [Shoonya-Dev/ShoonyaApi-py#3]
Traceback (most recent call last):
  File "E:\CODING\finvasiaAPI\shoonya\ShoonyaApi-py-master\example_market.py", line 75, in <module>
    ret = api.login(userid=cred['user'], password=cred['pwd'], twoFA=cred['factor2'],
  File "C:\Python310\lib\site-packages\NorenRestApiPy\NorenApi.py", line 231, in login
    res = requests.post(url, data=payload)
  File "C:\Python310\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(CertificateError("hostname 'shoonyatrade.finvasia.com' doesn't match either of 'shoonya.finvasia.com', 'www.shoonya.finvasia.com'")))

**Comment by Shoonya-Dev** [comment]
certificate is updated.

**Comment by pashriva** [comment]
+1

**Comment by avinashily** [comment]
i am getting the same error again today. please fix it.

*** requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLCertVerificationError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))

**Comment by rajeshhirpara** [comment]
I am also getting the same error again today. please fix it.

*** requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLCertVerificationError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))

**Comment by amolc** [comment]
Got this error today. Really are we 2 years still trying to solve the same problem. Need urgent help.

**Comment by sandeepvats1** [comment]
still getting the issue, is there any resolution to same

**Comment by Nitesh-bc** [comment]
[11:52:12] Login Error: HTTPSConnectionPool(host='api.shoonya.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)'))) SAME
