### ISSUE TITLE
Error while trying to login 

### ISSUE THREAD

**Issue by lokifr3k** [Shoonya-Dev/ShoonyaApi-py#42]
when i try to login getting the following error, it was working perfectly fine till yesterday(21-06-22) , error from today (22-06-22)

Traceback (most recent call last):
  File "c:\algo\fin\terminal\test.py", line 18, in <module>
    ret = api.login(userid=user, password=pwd, twoFA=factor2, vendor_code=vc, api_secret=app_key, imei=imei)
  File "C:\Users\mails\py\lib\site-packages\NorenRestApiPy\NorenApi.py", line 233, in login
    resDict = json.loads(res.text)
  File "C:\Users\mails\py\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mails\py\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mails\py\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lokifr3k** [comment]
fixed through customer care

**Comment by lokifr3k** [comment]
still the error is there , sometime it works fine , sometimes error is there.

**Comment by sakthi379** [comment]
i had login issues, resolved when i switched from vodafone to jio

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

As Per Your Confirmation, Your issue has been resolved after switch ISP.
