### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by rushey17** [Shoonya-Dev/ShoonyaApi-py#72]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rusheyandhaark/.local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(CertificateError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))****

**Comment by DeepBhuptani** [comment]
facing same error,

`requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(CertificateError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))`

**Comment by rushey17** [comment]
I think the error is because of expired SSL Certificate, Shoonya team need to update their SSL Certificate. 
They faced the similar certificate expired issue exactly one year before. 
You can see here, [https://github.com/Shoonya-Dev/ShoonyaApi-py/issues/3](url)

I could not believe that they did not have any automate machanism to update their SSL certificate.
This carelessness can lead to cause very serious issues for the algos running during realtime.
Hope it will resolve by the team and will not happen in future.

**Comment by pashriva** [comment]
+1

**Comment by bailakare** [comment]
facing same issue

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your concern.


Important Information:-
Those who have not yet shifted from the old endpoint URL to the new endpoint URL. We Request please update the new endpoint in your code. The old endpoint URL will be deprecated soon after some time.

NEW LIVE ENDPOINT URL:-        
host='https://api.shoonya.com/NorenWClientTP/'
websocket='wss://api.shoonya.com/NorenWSTP/'
eodhost='https://api.shoonya.com/chartApi/getdata/'
             
Team Finvasia.

**Comment by TheCodeArtist** [comment]
Anyone using this `ShoonyaApi-py` python package, and facing this issue,
please remember to use the latest version of `ShoonyaApi-py` available in this repo.

The commit https://github.com/Shoonya-Dev/ShoonyaApi-py/commit/db42175c12273bf8eb8129f932c6e6ced0bc70c2 updates the package to use the new end-point.
