### ISSUE TITLE
facing cirtificate issue can anyone help

### ISSUE THREAD

**Issue by siddup30** [Shoonya-Dev/ShoonyaApi-py#76]
Traceback (most recent call last):
  File "/Users/siddu/Documents/shoonya/stratergy2.py", line 10, in <module>
    ret = api.login(userid=config.user, password=config.pwd, twoFA=pyotp.TOTP(config.otpToken).now(), vendor_code=config.vc, api_secret=config.app_key, imei=config.imei)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/NorenRestApiPy/NorenApi.py", line 238, in login
    res = requests.post(url, data=payload)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(CertificateError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))

**Comment by TheCodeArtist** [comment]
Please remember to use the latest version of ShoonyaApi-py available in this repo.

The commit https://github.com/Shoonya-Dev/ShoonyaApi-py/commit/db42175c12273bf8eb8129f932c6e6ced0bc70c2 updates the package to use the new end-point.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.


**Kindly update the following URL in your code**

NEW LIVE ENDPOINT URL:-

host='https://api.shoonya.com/NorenWClientTP/'

websocket='wss://api.shoonya.com/NorenWSTP/'

eodhost='https://api.shoonya.com/chartApi/getdata/'
